apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meltingpoc-api-personnes
spec:
  replicas: 1
  template:
    metadata:
     labels:
        app: meltingpoc-api-personnes
    spec:
      containers:
      - name: meltingpoc-mongo
        image: mongo:3.5.13
        ports:
        - containerPort: 27017
      - name: meltingpoc-server
        image: registry.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc-api-personnes
        ports:
        - containerPort: 8080
      - env:
        - name: dropbox.token
          valueFrom:
            secretKeyRef:
              name: dropbox
              key: token
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  name: meltingpoc-api-personnes
spec:
  selector:
    app: meltingpoc-api-personnes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080