apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meltingpoc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
     labels:
        app: meltingpoc
    spec:
      containers:
      - name: meltingpoc-mongo
        image: mongo:3.5.13
        ports:
        - containerPort: 27017
      - name: meltingpoc-server
        image: registry.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: meltingpoc
spec:
  selector:
    app: meltingpoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meltingpoc
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: meltingpoc.k8.wildwidewest.xyz
    http:
      paths:
      - backend:
          serviceName: meltingpoc
          servicePort: 80